-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT Pro 17.0 (20161010))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 202202111029                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;

package JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   function Id_JNI_45 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean;

   function equals_Id_JNI_44 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean;
   pragma Export (C, equals_Id_JNI_44, "Java_hello_Standard_AdaString_equals_1Id_1JNI_144___3I_3I");

   function Id_JNI_72 (This : access Standard.String) return access Standard.String;

   function internalClone_Id_JNI_71 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, internalClone_Id_JNI_71, "Java_hello_Standard_AdaString_internalClone_1Id_1JNI_171___3I");

   function Id_JNI_94 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String;

   function AdaString_Id_JNI_93 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, AdaString_Id_JNI_93, "Java_hello_Standard_AdaString_AdaString_1Id_1JNI_193__II");

   procedure Id_JNI_107 (Obj : access Standard.String);

   procedure deallocateNativeObject_Id_JNI_106 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array);
   pragma Export (C, deallocateNativeObject_Id_JNI_106, "Java_hello_Standard_AdaString_deallocateNativeObject_1Id_1JNI_1106___3I");

   function Id_JNI_119 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character;

   function Get_Element_At_Id_JNI_118 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char;
   pragma Export (C, Get_Element_At_Id_JNI_118, "Java_hello_Standard_AdaString_Get_1Element_1At_1Id_1JNI_1118___3II");

   procedure Id_JNI_139 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character);

   procedure Set_Element_At_Id_JNI_138 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char);
   pragma Export (C, Set_Element_At_Id_JNI_138, "Java_hello_Standard_AdaString_Set_1Element_1At_1Id_1JNI_1138___3IIC");

   function Id_JNI_152 (This : Standard.String) return Standard.Integer'Base;

   function First_Id_JNI_151 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, First_Id_JNI_151, "Java_hello_Standard_AdaString_First_1Id_1JNI_1151___3I");

   function Id_JNI_170 (This : Standard.String) return Standard.Integer'Base;

   function Last_Id_JNI_169 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, Last_Id_JNI_169, "Java_hello_Standard_AdaString_Last_1Id_1JNI_1169___3I");

   function Id_JNI_188 (This : Standard.String) return Standard.Integer;

   function Length_Id_JNI_187 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int;
   pragma Export (C, Length_Id_JNI_187, "Java_hello_Standard_AdaString_Length_1Id_1JNI_1187___3I");

   function Id_JNI_206 return access Standard.String;

   function createNullAccess_Id_JNI_205 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, createNullAccess_Id_JNI_205, "Java_hello_Standard_AdaString_createNullAccess_1Id_1JNI_1205__");

   function Id_JNI_218 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String;

   function toString_Id_JNI_217 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object;
   pragma Export (C, toString_Id_JNI_217, "Java_hello_Standard_AdaString_toString_1Id_1JNI_1217___3I");

   function Id_JNI_235 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;

   function AdaString_Id_JNI_234 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array;
   pragma Export (C, AdaString_Id_JNI_234, "Java_hello_Standard_AdaString_AdaString_1Id_1JNI_1234__Ljava_lang_String_2");

   Id_JNI_42 : AJIS.Internal.Java.Java_Method_Access := AJIS.Internal.Java.Get_Java_Method ("hello/Standard/AdaString", "<init>", "(Lcom/adacore/ajis/internal/ada/AdaAccess;)V");

end JNI_Binding.Standard_JNI.AdaString_JNI;
