-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT Pro 17.0 (20161010))          --
-- Original Ada unit: Hello_Pkg                                              --
-- Generation timestamp: 202202111029                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Hello_Pkg; use Hello_Pkg;

package JNI_Binding.Hello_Pkg_JNI.Hello_Pkg_Package_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

   procedure Id_JNI_40 (Item : Standard.Integer);

   procedure Hello_Id_JNI_39 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class; Item : Interfaces.Java.JNI.J_Int);
   pragma Export (C, Hello_Id_JNI_39, "Java_hello_Hello_1Pkg_Hello_1Pkg_1Package_Hello_1Id_1JNI_139__I");

end JNI_Binding.Hello_Pkg_JNI.Hello_Pkg_Package_JNI;
