-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT Pro 17.0 (20161010))          --
-- Original Ada unit: Standard                                               --
-- Generation timestamp: 202202111029                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Ada.Unchecked_Deallocation;
with System.Address_To_Access_Conversions;
with Ada.Unchecked_Conversion;
with Ada.Tags;
with Ada.Exceptions;
with Interfaces.C;
with Interfaces.C.Strings;

package body JNI_Binding.Standard_JNI.AdaString_JNI is 

   procedure JNI_For_Body_Elaboration is begin null; end;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access) is
   begin

      null;
      AJIS.Internal.Java.Initialize (Id_JNI_42, Id_JNI_1);
   end Initialize_Unit_JNI;

   function Id_JNI_45 (Left : access constant Standard.String; Right : access constant Standard.String) return Standard.Boolean is
      Id_JNI_65 : Standard.Boolean := Standard."=" (Left.all, Right.all);
   begin
      return Id_JNI_65;
   end Id_JNI_45;

   function equals_Id_JNI_44 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Left : Interfaces.Java.JNI.J_Int_J_Array; Right : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Boolean is
   begin
      declare
         Id_JNI_47 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, Left);
         Id_JNI_52 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_47);
         subtype Id_JNI_48 is Standard.String (Id_JNI_47.Bound_1_Low .. Id_JNI_47.Bound_1_High);
         type Id_JNI_49 is access all Id_JNI_48;
         package Id_JNI_50 is new System.Address_To_Access_Conversions (Id_JNI_48);
         Id_JNI_51 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_47.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_51 := Id_JNI_50.To_Pointer (Id_JNI_52).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_47.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_51 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_47.General_Pointer);
         else
            Id_JNI_51 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_47.Constant_Pointer);
         end if;
         declare
            Id_JNI_56 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, Right);
            Id_JNI_61 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_56);
            subtype Id_JNI_57 is Standard.String (Id_JNI_56.Bound_1_Low .. Id_JNI_56.Bound_1_High);
            type Id_JNI_58 is access all Id_JNI_57;
            package Id_JNI_59 is new System.Address_To_Access_Conversions (Id_JNI_57);
            Id_JNI_60 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
         begin
            if AJIS.Internal.Java."=" (Id_JNI_56.Kind, AJIS.Internal.Java.Static) then
               Id_JNI_60 := Id_JNI_59.To_Pointer (Id_JNI_61).all'Unrestricted_Access;
            elsif AJIS.Internal.Java."=" (Id_JNI_56.Kind, AJIS.Internal.Java.General_Access) then
               Id_JNI_60 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_56.General_Pointer);
            else
               Id_JNI_60 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_56.Constant_Pointer);
            end if;
            declare
               Id_JNI_66 : Interfaces.Java.JNI.J_Boolean := Interfaces.Java.JNI.J_Boolean (Id_JNI_45 (Id_JNI_51, Id_JNI_60));
            begin
               return Id_JNI_66;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Boolean (False);
         end;
   end equals_Id_JNI_44;

   function Id_JNI_72 (This : access Standard.String) return access Standard.String is
      Id_JNI_82 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := new Standard.String'(This.all);
      Id_JNI_87 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_82);
   begin
      return Id_JNI_87;
   end Id_JNI_72;

   function internalClone_Id_JNI_71 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_74 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_79 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_74);
         subtype Id_JNI_75 is Standard.String (Id_JNI_74.Bound_1_Low .. Id_JNI_74.Bound_1_High);
         type Id_JNI_76 is access all Id_JNI_75;
         package Id_JNI_77 is new System.Address_To_Access_Conversions (Id_JNI_75);
         Id_JNI_78 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_74.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_78 := Id_JNI_77.To_Pointer (Id_JNI_79).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_74.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_78 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_74.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_84_Proxy : Interfaces.Java.JNI.J_Object;
            Id_JNI_85_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_72 (Id_JNI_78))));
         begin
            declare
               Id_JNI_88 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_85_Ptr);
            begin
               return Id_JNI_88;
            end;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end internalClone_Id_JNI_71;

   function Id_JNI_94 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Standard.Integer'Base; Last_1 : Standard.Integer'Base) return access Standard.String is
      Id_JNI_101 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer'( new Standard.String (First_1 .. Last_1)));
   begin
      return Id_JNI_101;
   end Id_JNI_94;

   function AdaString_Id_JNI_93 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; First_1 : Interfaces.Java.JNI.J_Int; Last_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_98_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_99_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_94(Id_JNI_1, Id_JNI_2, Standard.Integer'Base (First_1), Standard.Integer'Base (Last_1)))));
      begin
         declare
            Id_JNI_102 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_99_Ptr);
         begin
            return Id_JNI_102;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_93;

   procedure Id_JNI_107 (Obj : access Standard.String) is
      Id_JNI_117 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Obj);
   begin
      JNI_Binding.Standard_JNI.Id_JNI_43.Free (Id_JNI_117);
   end Id_JNI_107;

   procedure deallocateNativeObject_Id_JNI_106 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Obj : Interfaces.Java.JNI.J_Int_J_Array) is
   begin
      declare
         Id_JNI_109 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, Obj);
         Id_JNI_114 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_109);
         subtype Id_JNI_110 is Standard.String (Id_JNI_109.Bound_1_Low .. Id_JNI_109.Bound_1_High);
         type Id_JNI_111 is access all Id_JNI_110;
         package Id_JNI_112 is new System.Address_To_Access_Conversions (Id_JNI_110);
         Id_JNI_113 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_109.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_113 := Id_JNI_112.To_Pointer (Id_JNI_114).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_109.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_113 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_109.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_107 (Id_JNI_113);
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end deallocateNativeObject_Id_JNI_106;

   function Id_JNI_119 (This : access Standard.String; Index_1 : Standard.Integer'Base) return Standard.Character is
      Id_JNI_132 : Standard.Character := This (Index_1);
   begin
      return Id_JNI_132;
   end Id_JNI_119;

   function Get_Element_At_Id_JNI_118 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int) return Interfaces.Java.JNI.J_Char is
   begin
      declare
         Id_JNI_121 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_126 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_121);
         subtype Id_JNI_122 is Standard.String (Id_JNI_121.Bound_1_Low .. Id_JNI_121.Bound_1_High);
         type Id_JNI_123 is access all Id_JNI_122;
         package Id_JNI_124 is new System.Address_To_Access_Conversions (Id_JNI_122);
         Id_JNI_125 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_121.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_125 := Id_JNI_124.To_Pointer (Id_JNI_126).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_121.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_125 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_121.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
            Id_JNI_133 : Interfaces.Java.JNI.J_Char := Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (Id_JNI_119 (Id_JNI_125, Standard.Integer'Base (Index_1))));
         begin
            return Id_JNI_133;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Char (Ada.Characters.Conversions.To_Wide_Character (ASCII.NUL));
         end;
   end Get_Element_At_Id_JNI_118;

   procedure Id_JNI_139 (This : access Standard.String; Index_1 : Standard.Integer'Base; Value : Standard.Character) is
   begin
      This (Index_1) := Value;
   end Id_JNI_139;

   procedure Set_Element_At_Id_JNI_138 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array; Index_1 : Interfaces.Java.JNI.J_Int; Value : Interfaces.Java.JNI.J_Char) is
   begin
      declare
         Id_JNI_141 : constant JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_146 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_141);
         subtype Id_JNI_142 is Standard.String (Id_JNI_141.Bound_1_Low .. Id_JNI_141.Bound_1_High);
         type Id_JNI_143 is access all Id_JNI_142;
         package Id_JNI_144 is new System.Address_To_Access_Conversions (Id_JNI_142);
         Id_JNI_145 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_141.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_145 := Id_JNI_144.To_Pointer (Id_JNI_146).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_141.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_145 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_141.General_Pointer);
         else
            raise Standard.Constraint_Error with "Object stored is not access to constant.";
         end if;
         declare
         begin
            Id_JNI_139 (Id_JNI_145, Standard.Integer'Base (Index_1), Standard.Character (Ada.Characters.Conversions.To_Character (Wide_Character (Value))));
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
         end;
   end Set_Element_At_Id_JNI_138;

   function Id_JNI_152 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_163 : Standard.Integer'Base := This'First;
   begin
      return Id_JNI_163;
   end Id_JNI_152;

   function First_Id_JNI_151 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_154 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_159 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_154);
         subtype Id_JNI_155 is Standard.String (Id_JNI_154.Bound_1_Low .. Id_JNI_154.Bound_1_High);
         type Id_JNI_156 is access all Id_JNI_155;
         package Id_JNI_157 is new System.Address_To_Access_Conversions (Id_JNI_155);
         Id_JNI_158 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_154.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_158 := Id_JNI_157.To_Pointer (Id_JNI_159).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_154.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_158 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_154.General_Pointer);
         else
            Id_JNI_158 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_154.Constant_Pointer);
         end if;
         declare
            Id_JNI_164 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_152 (Standard.String (Id_JNI_158.all)));
         begin
            return Id_JNI_164;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end First_Id_JNI_151;

   function Id_JNI_170 (This : Standard.String) return Standard.Integer'Base is
      Id_JNI_181 : Standard.Integer'Base := This'Last;
   begin
      return Id_JNI_181;
   end Id_JNI_170;

   function Last_Id_JNI_169 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_172 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_177 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_172);
         subtype Id_JNI_173 is Standard.String (Id_JNI_172.Bound_1_Low .. Id_JNI_172.Bound_1_High);
         type Id_JNI_174 is access all Id_JNI_173;
         package Id_JNI_175 is new System.Address_To_Access_Conversions (Id_JNI_173);
         Id_JNI_176 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_172.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_176 := Id_JNI_175.To_Pointer (Id_JNI_177).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_172.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_176 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_172.General_Pointer);
         else
            Id_JNI_176 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_172.Constant_Pointer);
         end if;
         declare
            Id_JNI_182 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_170 (Standard.String (Id_JNI_176.all)));
         begin
            return Id_JNI_182;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Last_Id_JNI_169;

   function Id_JNI_188 (This : Standard.String) return Standard.Integer is
      Id_JNI_199 : Standard.Integer := This'Length;
   begin
      return Id_JNI_199;
   end Id_JNI_188;

   function Length_Id_JNI_187 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Int is
   begin
      declare
         Id_JNI_190 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_195 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_190);
         subtype Id_JNI_191 is Standard.String (Id_JNI_190.Bound_1_Low .. Id_JNI_190.Bound_1_High);
         type Id_JNI_192 is access all Id_JNI_191;
         package Id_JNI_193 is new System.Address_To_Access_Conversions (Id_JNI_191);
         Id_JNI_194 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_190.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_194 := Id_JNI_193.To_Pointer (Id_JNI_195).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_190.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_194 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_190.General_Pointer);
         else
            Id_JNI_194 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_190.Constant_Pointer);
         end if;
         declare
            Id_JNI_200 : Interfaces.Java.JNI.J_Int := Interfaces.Java.JNI.J_Int (Id_JNI_188 (Standard.String (Id_JNI_194.all)));
         begin
            return Id_JNI_200;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return 0;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return 0;
         end;
   end Length_Id_JNI_187;

   function Id_JNI_206 return access Standard.String is
      Id_JNI_211 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer'(null));
   begin
      return Id_JNI_211;
   end Id_JNI_206;

   function createNullAccess_Id_JNI_205 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_3 : Interfaces.Java.JNI.J_Class) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_208_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_209_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_206)));
      begin
         declare
            Id_JNI_212 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_209_Ptr);
         begin
            return Id_JNI_212;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end createNullAccess_Id_JNI_205;

   function Id_JNI_218 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; This : Standard.String) return Interfaces.Java.JNI.J_String is
      Id_JNI_228 : Interfaces.C.Strings.chars_ptr;
      Id_JNI_229 : Interfaces.Java.JNI.J_String;
   begin
      Id_JNI_228 := Interfaces.C.Strings.New_String (String (This));
      Id_JNI_229 := Interfaces.Java.JNI.New_String_UTF (Id_JNI_1, Id_JNI_228);
      Interfaces.C.Strings.Free (Id_JNI_228);
      return Id_JNI_229;
   end Id_JNI_218;

   function toString_Id_JNI_217 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; This : Interfaces.Java.JNI.J_Int_J_Array) return Interfaces.Java.JNI.J_Object is
   begin
      declare
         Id_JNI_220 : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.To_Object_Pointer (Id_JNI_1, This);
         Id_JNI_225 : constant System.Address := JNI_Binding.Standard_JNI.Id_JNI_43.Get_Address (Id_JNI_220);
         subtype Id_JNI_221 is Standard.String (Id_JNI_220.Bound_1_Low .. Id_JNI_220.Bound_1_High);
         type Id_JNI_222 is access all Id_JNI_221;
         package Id_JNI_223 is new System.Address_To_Access_Conversions (Id_JNI_221);
         Id_JNI_224 : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst;
      begin
         if AJIS.Internal.Java."=" (Id_JNI_220.Kind, AJIS.Internal.Java.Static) then
            Id_JNI_224 := Id_JNI_223.To_Pointer (Id_JNI_225).all'Unrestricted_Access;
         elsif AJIS.Internal.Java."=" (Id_JNI_220.Kind, AJIS.Internal.Java.General_Access) then
            Id_JNI_224 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_220.General_Pointer);
         else
            Id_JNI_224 := JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer_Cst (Id_JNI_220.Constant_Pointer);
         end if;
         declare
            Id_JNI_230 : Interfaces.Java.JNI.J_Object := Id_JNI_218 (Id_JNI_1, Standard.String (Id_JNI_224.all));
         begin
            return Id_JNI_230;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Object;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Object;
         end;
   end toString_Id_JNI_217;

   function Id_JNI_235 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_String) return JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer is
      Is_Copy : aliased Interfaces.Java.JNI.J_Boolean;
      C_Str : constant Interfaces.C.Strings.chars_ptr := Interfaces.Java.JNI.Get_String_UTF_Chars (Id_JNI_1, Str, Is_Copy'Unchecked_Access);
      Ada_Str : constant AJIS.Internal.Java.Unchecked_String_Access := AJIS.Internal.Java.To_Unchecked_String (AJIS.Internal.Java.Convert (C_Str));
      pragma Suppress (Access_Check, Ada_Str);
      Result : JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer := new Standard.String'(Standard.String (Ada_Str (1 .. Integer (Interfaces.C.Strings.Strlen (C_Str)))));
   begin
      Interfaces.Java.JNI.Release_String_UTF_Chars (Id_JNI_1, Str, C_Str);
      return Result;
   end Id_JNI_235;

   function AdaString_Id_JNI_234 (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access; Id_JNI_2 : Interfaces.Java.JNI.J_Object; Str : Interfaces.Java.JNI.J_Object) return Interfaces.Java.JNI.J_Int_J_Array is
   begin
      declare
         Id_JNI_238_Proxy : Interfaces.Java.JNI.J_Object;
         Id_JNI_239_Ptr : JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer := JNI_Binding.Standard_JNI.Id_JNI_43.Object_Pointer (JNI_Binding.Standard_JNI.Id_JNI_43.Create_General_Encapsulation (JNI_Binding.Standard_JNI.Id_JNI_43.Array_Pointer (Id_JNI_235(Id_JNI_1, Id_JNI_2, Str))));
      begin
         declare
            Id_JNI_241 : Interfaces.Java.JNI.J_Int_J_Array := JNI_Binding.Standard_JNI.Id_JNI_43.To_J_Int_J_Array (Id_JNI_1, Id_JNI_239_Ptr);
         begin
            return Id_JNI_241;
         end;
      end;
   exception
      when J : AJIS.Java.Java_Exception =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
         begin
            Result := Interfaces.Java.JNI.Throw (Id_JNI_1, AJIS.Internal.Java.Throwable_Value (Ada.Exceptions.Exception_Message (J)));
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
      when E : others =>
         declare
            Result : Interfaces.Java.JNI.J_Int;
            Except : Interfaces.Java.JNI.J_Object;
         begin
            Except := AJIS.Internal.Java.Create_Java_Exception (Id_JNI_1, E);
            if Interfaces.Java.JNI."=" (Except, Interfaces.Java.JNI.J_Null_Object) then
               Result := Interfaces.Java.JNI.Throw_New (Id_JNI_1, AJIS.Internal.Java.Get_Class (AJIS.Internal.Java.Native_Exception_Class), Interfaces.C.To_C (Ada.Exceptions.Exception_Information (E)));
            else
               Result := Interfaces.Java.JNI.Throw (Id_JNI_1, Except);
            end if;
            return Interfaces.Java.JNI.J_Null_Int_J_Array;
         end;
   end AdaString_Id_JNI_234;

begin
   null;
end JNI_Binding.Standard_JNI.AdaString_JNI;
