-------------------------------------------------------------------------------
-- This file has been automatically generated by                             --
--    ADA2JAVA (built with ASIS 2.0.R for GNAT Pro 17.0 (20161010))          --
-- Original Ada unit: Hello_Pkg                                              --
-- Generation timestamp: 202202111029                                        --
-------------------------------------------------------------------------------

pragma Warnings (Off);
pragma Style_Checks ("NM32766");

with Interfaces.Java.JNI;
with AJIS;
with AJIS.Internal;
with AJIS.Java;
with AJIS.Internal.Java;
with Ada.Characters.Conversions;
with Ada.Finalization;
with Hello_Pkg; use Hello_Pkg;
with JNI_Binding.Standard_JNI;

package JNI_Binding.Hello_Pkg_JNI is 

   procedure JNI_For_Body_Elaboration;

   procedure Initialize_Unit_JNI (Id_JNI_1 : Interfaces.Java.JNI.JNI_Env_Access);

end JNI_Binding.Hello_Pkg_JNI;
