/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT Pro 17.0 (20161010))          *
 * Original Ada unit: Hello_Pkg                                              *
 * Generation timestamp: 202202111029                                        *
 *****************************************************************************/

package hello.Hello_Pkg;

/**
 * @origin hello_pkg.ads:1:09
 */
@SuppressWarnings("all")
public final class Hello_Pkg_Package {

   /**
    * @origin hello_pkg.ads:2:14
    */
   static public void Hello (int Item) {
      hello.Ada2Java.Library.lock.lock ();
      try {
         Hello_Id_JNI_39 (Item);
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // Hello

   native static private void Hello_Id_JNI_39 (int Item);

   static {
      hello.Ada2Java.Library.load ();
   }

} // Hello_Pkg_Package
