/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT Pro 17.0 (20161010))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 202202111029                                        *
 *****************************************************************************/

package hello.Standard;

/**
 */
@SuppressWarnings("all")
public final class AdaString extends com.adacore.ajis.internal.ada.AdaProxy {

   /**
    * @param this is passed by reference (non escapable)
    * @param Right is passed by reference (non escapable)
    */
   final public boolean equals (java.lang.Object Right) {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_53;
         java.lang.Object Id_JNI_54 = this;
         if (this.getClass () != Right.getClass ()) return false;
         if (Id_JNI_54 == null) {
            Id_JNI_53 = hello.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_53 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_54).getAccess ();
         }
         int [] Id_JNI_62;
         java.lang.Object Id_JNI_63 = ((com.adacore.ajis.internal.ada.AdaProxy) Right);
         if (Id_JNI_63 == null) {
            Id_JNI_62 = hello.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_62 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_63).getAccess ();
         }
         boolean Id_JNI_67 = equals_Id_JNI_44 (Id_JNI_53, Id_JNI_62);
         return Id_JNI_67;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // equals

   /**
    * @param this is passed by reference (non escapable)
    * @return is passed by reference (escapable)
    */
   public int [] internalClone () {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_80;
         hello.Standard.AdaString Id_JNI_81 = this;
         if (Id_JNI_81 == null) {
            Id_JNI_80 = hello.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_80 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_81).getAccess ();
         }
         int [] Id_JNI_89 = ((int []) internalClone_Id_JNI_71 (Id_JNI_80));
         return Id_JNI_89;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // internalClone

   /**
    * @return is passed by reference (escapable)
    */
   public AdaString (int First_1, int Last_1) {
      super (new com.adacore.ajis.internal.ada.AdaAccess (null));
      hello.Ada2Java.Library.lock.lock ();
      try {
         this.adaAccess = AdaString_Id_JNI_93 (First_1, Last_1);
         this.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         this.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // AdaString

   public AdaString (com.adacore.ajis.internal.ada.AdaAccess access) {
      this.adaAccess = access.fAcc;
   }

   /**
    * @param this is passed by reference (non escapable)
    */
   public void deallocateNativeObject () {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_115;
         hello.Standard.AdaString Id_JNI_116 = this;
         if (Id_JNI_116 == null) {
            Id_JNI_115 = hello.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_115 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_116).getAccess ();
         }
         deallocateNativeObject_Id_JNI_106 (Id_JNI_115);
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // deallocateNativeObject

   /**
    * @param this is passed by reference (non escapable)
    */
   final public char Get_Element_At (int Index_1) {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_127;
         hello.Standard.AdaString Id_JNI_128 = this;
         if (Id_JNI_128 == null) {
            Id_JNI_127 = hello.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_127 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_128).getAccess ();
         }
         char Id_JNI_134 = Get_Element_At_Id_JNI_118 (Id_JNI_127, Index_1);
         return Id_JNI_134;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // Get_Element_At

   /**
    * @param this is passed by reference (non escapable)
    */
   final public void Set_Element_At (int Index_1, char Value) {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_147;
         hello.Standard.AdaString Id_JNI_148 = this;
         if (Id_JNI_148 == null) {
            Id_JNI_147 = hello.Standard.AdaString.nullArrayAccess ();
         } else {
            Id_JNI_147 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_148).getAccess ();
         }
         Set_Element_At_Id_JNI_138 (Id_JNI_147, Index_1, Value);
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // Set_Element_At

   /**
    * @param this is passed by value
    */
   final public int First () {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_160;
         hello.Standard.AdaString Id_JNI_161 = this;
         Id_JNI_160 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_161).getAccess ();
         int Id_JNI_165 = First_Id_JNI_151 (Id_JNI_160);
         return Id_JNI_165;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // First

   /**
    * @param this is passed by value
    */
   final public int Last () {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_178;
         hello.Standard.AdaString Id_JNI_179 = this;
         Id_JNI_178 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_179).getAccess ();
         int Id_JNI_183 = Last_Id_JNI_169 (Id_JNI_178);
         return Id_JNI_183;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // Last

   /**
    * @param this is passed by value
    */
   final public int Length () {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_196;
         hello.Standard.AdaString Id_JNI_197 = this;
         Id_JNI_196 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_197).getAccess ();
         int Id_JNI_201 = Length_Id_JNI_187 (Id_JNI_196);
         return Id_JNI_201;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // Length

   /**
    * @return is passed by reference (escapable)
    */
   static public int [] createNullAccess () {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_213 = ((int []) createNullAccess_Id_JNI_205 ());
         return Id_JNI_213;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // createNullAccess

   private static int [] nullArrayAccessVal;

   public static int [] nullArrayAccess () {
      if (nullArrayAccessVal == null) {
         nullArrayAccessVal = createNullAccess ();
      }
      return nullArrayAccessVal;
   }

   /**
    * @param this is passed by value
    * @return is passed by value
    */
   final public java.lang.String toString () {
      hello.Ada2Java.Library.lock.lock ();
      try {
         int [] Id_JNI_226;
         hello.Standard.AdaString Id_JNI_227 = this;
         Id_JNI_226 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_227).getAccess ();
         java.lang.String Id_JNI_231 = toString_Id_JNI_217 (Id_JNI_226);
         return Id_JNI_231;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // toString

   /**
    * @param Str is passed by value
    * @return is passed by reference (escapable)
    */
   public AdaString (java.lang.String Str) {
      hello.Ada2Java.Library.lock.lock ();
      try {
         java.lang.String Id_JNI_236 = Str;
         if (Id_JNI_236 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Str");
         }
         this.adaAccess = AdaString_Id_JNI_234 (Id_JNI_236);
         this.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
         this.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // AdaString

   native private boolean equals_Id_JNI_44 (int [] Left, int [] Right);

   native private int [] internalClone_Id_JNI_71 (int [] This);

   native private int [] AdaString_Id_JNI_93 (int First_1, int Last_1);

   native private void deallocateNativeObject_Id_JNI_106 (int [] Obj);

   native private char Get_Element_At_Id_JNI_118 (int [] This, int Index_1);

   native private void Set_Element_At_Id_JNI_138 (int [] This, int Index_1, char Value);

   native private int First_Id_JNI_151 (int [] This);

   native private int Last_Id_JNI_169 (int [] This);

   native private int Length_Id_JNI_187 (int [] This);

   native static private int [] createNullAccess_Id_JNI_205 ();

   native private java.lang.String toString_Id_JNI_217 (int [] This);

   native private int [] AdaString_Id_JNI_234 (java.lang.String Str);

   static {
      hello.Ada2Java.Library.load ();
   }

} // AdaString
