/*****************************************************************************
 * This file has been automatically generated by                             *
 *    ADA2JAVA (built with ASIS 2.0.R for GNAT Pro 17.0 (20161010))          *
 * Original Ada unit: Standard                                               *
 * Generation timestamp: 202202111029                                        *
 *****************************************************************************/

package hello.Standard;

/**
 */
@SuppressWarnings("all")
public final class Storage_Error extends com.adacore.ajis.NativeException implements com.adacore.ajis.internal.ada.AdaException {

   hello.Ada.Exceptions.Exception_Occurrence Id_JNI_292;

   private Storage_Error (String message, int [] addr) {
      super (message);
      Id_JNI_292 = new hello.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (addr));
      Id_JNI_292.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
      Id_JNI_292.myOwner = com.adacore.ajis.IProxy.Owner.PROXY;
   }

   public Storage_Error (hello.Standard.AdaString message) {
      super (message.toString());
      Id_JNI_292 = createOccurrence (message);
   }

   public int [] getExceptionAddr () {
      return Id_JNI_292.getAccess ();
   }

   /**
    * @param Message is passed by value
    * @return is passed by reference (escapable)
    */
   static public hello.Ada.Exceptions.Exception_Occurrence createOccurrence (hello.Standard.AdaString Message) {
      hello.Ada2Java.Library.lock.lock ();
      try {
         hello.Standard.AdaString Id_JNI_295 = Message;
         if (Id_JNI_295 == null) {
            throw new com.adacore.ajis.NativeException ("null not allowed for Message");
         }
         int [] Id_JNI_302;
         hello.Standard.AdaString Id_JNI_303 = Id_JNI_295;
         Id_JNI_302 = ((com.adacore.ajis.internal.ada.AdaProxy) Id_JNI_303).getAccess ();
         int [] Id_JNI_308 = createOccurrence_Id_JNI_293 (Id_JNI_302);
         hello.Ada.Exceptions.Exception_Occurrence Id_JNI_309;
         if (com.adacore.ajis.internal.ada.AdaAccess.isNull (Id_JNI_308)) {
            Id_JNI_309 = null;
         } else {
            Id_JNI_309 = new hello.Ada.Exceptions.Exception_Occurrence (new com.adacore.ajis.internal.ada.AdaAccess (Id_JNI_308));
         }
         hello.Ada.Exceptions.Exception_Occurrence Id_JNI_310 = Id_JNI_309;
         if (Id_JNI_310 != null) {
            Id_JNI_310.myAllocator = com.adacore.ajis.IProxy.Allocator.DYNAMIC;
         }
         hello.Ada.Exceptions.Exception_Occurrence Id_JNI_313 = Id_JNI_310;
         return Id_JNI_313;
      } finally {
         hello.Ada2Java.Library.lock.unlock ();
      }
   } // createOccurrence

   native static private int [] createOccurrence_Id_JNI_293 (int [] Message);

   static {
      hello.Ada2Java.Library.load ();
   }

} // Storage_Error
